import Image from "next/image";
import Link from "next/link";
import { AppWindow, ArrowLeft, ExternalLink, GitFork, Globe, Shield, Smartphone, Trash2 } from "lucide-react";
import { ScreenshotCarousel } from "./screenshot-carousel";
import type { AppItem } from "@/data/types";

export function AppDetailView({ app }: { app: AppItem }) {
  const links = [
    app.appStoreUrl && { icon: Smartphone, label: "App Store", href: app.appStoreUrl }, app.playStoreUrl && { icon: AppWindow, label: "Play Store", href: app.playStoreUrl }, app.websiteUrl && { icon: Globe, label: "Website", href: app.websiteUrl }, app.githubUrl && { icon: GitFork, label: "GitHub", href: app.githubUrl }, app.otherUrl && { icon: ExternalLink, label: app.otherUrlLabel ?? "Open link", href: app.otherUrl },
  ].filter(Boolean) as Array<{ icon: React.ElementType; label: string; href: string }>;
  return <article className="editorial-project"><Link href="/apps" className="editorial-back"><ArrowLeft size={16} /> All apps</Link><header className="editorial-project-header"><div><div className="editorial-project-meta"><Image src={app.appIconSrc} alt={app.appIconAlt} width={96} height={96} priority /><span>{app.appType}</span><span>{app.category || app.workType}</span></div><h1>{app.title}</h1><p>{app.tagline}</p></div><small>{app.period}</small></header><ScreenshotCarousel screenshots={app.screenshots} appTitle={app.title} /><div className="editorial-project-layout"><aside><span>BUILD KIT</span><div className="editorial-tags">{app.stack.map((item) => <span key={item}>{item}</span>)}</div>{links.length ? <div className="editorial-project-links">{links.map(({ icon: Icon, ...link }) => <a key={link.label} href={link.href} target="_blank" rel="noreferrer"><Icon size={16} />{link.label}</a>)}</div> : null}</aside><div className="editorial-project-copy"><section><h2>About the app</h2><p>{app.description}</p></section>{app.highlights.length ? <section><h2>What it does</h2><ul>{app.highlights.map((item) => <li key={item}>{item}</li>)}</ul></section> : null}{app.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.entries.map((entry, index) => <div key={`${section.title}-${index}`}>{entry.title ? <h3>{entry.title}</h3> : null}{entry.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{entry.bullets.length ? <ul>{entry.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}{entry.codeBlocks.map((block, blockIndex) => <pre key={blockIndex}><code>{block.content}</code></pre>)}</div>)}</section>)}</div></div>{app.hasPrivacyPolicy || app.hasAccountDeletion ? <section className="editorial-project-legal"><span>LEGAL</span><div>{app.hasPrivacyPolicy ? <Link href={`/apps/${app.slug}/privacy-policy`}><Shield size={16} /> Privacy Policy</Link> : null}{app.hasAccountDeletion ? <Link href={`/apps/${app.slug}/account-deletion`}><Trash2 size={16} /> Account Deletion</Link> : null}</div></section> : null}</article>;
}
